### PR TITLE
Allow using custom request class

### PR DESCRIPTION
**Pull request by Smlep**
Hey

My team and I came across a use case where we needed to allow some extra fields in the first level of the Json-RPC payload request.

So I added an option to use a custom *JsonRpcRequest* class, inheriting from the initial `fastapi-jsonrpc`'s JsonRpcRequest class.

The usage is the following:

```python

import fastapi_jsonrpc as jsonrpc

from fastapi.middleware.cors import CORSMiddleware
from fastapi import Body
from fastapi_jsonrpc import JsonRpcRequest

app = jsonrpc.API()

app.add_middleware(CORSMiddleware, allow_origins=["*"])


class CustomJsonRpcRequest(JsonRpcRequest):
    extravalue: str

api_v1 = jsonrpc.Entrypoint("/api", request_class=CustomJsonRpcRequest)


@api_v1.method()
def echo(
    data: str = Body(..., example="123"),
) -> dict:
    return {"from": "echo", "data": data}


app.bind_entrypoint(api_v1)
```

This example allows receiving this payload:

```json
  id: 0,
  jsonrpc: "2.0",
  method: "echo",
  params: {data: "testdata"},
  extravalue: "test"
```

I hope you'll find this feature useful 👍.

### CODE REVIEW

**Comment by smagafurov** [comment]
Hi!

fastapi-jsonrpc (2.1.0)

**Comment by spumer** [comment]
@Smlep can you add some tests to ensure this feature will not be broken in future?

**Comment by Smlep** [comment]
@spumer Ok, I will

**Comment by Smlep** [comment]
Here you go @spumer 
https://github.com/smagafurov/fastapi-jsonrpc/pull/22

**Pull request merged**
